# Generated by Django 2.1.15 on 2024-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20240308_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternate_mobile_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_mobile_number',
            field=models.IntegerField(null=True),
        ),
    ]
