# Generated by Django 2.1.15 on 2024-05-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20240419_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
